title: Tyler Bradford # your name (or website title) here
logo: "/images/Tyler.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Masters of City Planning Candidate 2021, University of Pennsylvania
  <br><br>
  Data scientist/analyst working at the intersection of urban planning and technology with a passion for data driven approacheslife that improve cities and their lives. Previous expeience in micromobility and bikeshare at Motivate / Citibike in New York City. Also experienced in international development and community-based work through the U.S. Peace Corps. Interested in geospatial analysis, GIS, urban planning, transportation, and environmental management. Passionate about social justice, maps, and all things Madagascar. 
  <br><br>
  <a href="https://www.linkedin.com/in/ctylerbradford/">View My LinkedIn Profile</a>
  <br><br> 
  
theme: jekyll-theme-minimal
