title: Tyler Bradford # your name (or website title) here
logo: "/images/Tyler.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Masters of City Planning Candidate 2021, University of Pennsylvania
  <br><br>
  Data scientist & analyst working at the intersection of urban planning and technology with a passion for data driven approaches that improve cities and lives. Previous expeience in micromobility and international development. Interested in geospatial analysis, urban planning, transportation, and environmental management.
  <br><br>
  <a href="https://www.linkedin.com/in/ctylerbradford/">View My LinkedIn Profile</a>
  <br><br> 
  
theme: jekyll-theme-minimal
